import { Template } from 'e2b'

export const template = Template()
  .fromImage('python:3.11-slim')
  .setUser('root')
  .setWorkdir('/')
  .runCmd('apt-get update && apt-get install -y curl git wget build-essential libgomp1 && apt-get clean && rm -rf /var/lib/apt/lists/*')
  .runCmd('pip install --upgrade pip -q')
  .runCmd('pip install -q numpy pandas scikit-learn matplotlib seaborn xgboost lightgbm optuna joblib pillow requests')
  .runCmd('pip install -q torch torchvision --index-url https://download.pytorch.org/whl/cpu')
  .runCmd('pip install -q transformers datasets tokenizers accelerate')
  .runCmd('pip install -q fastapi uvicorn[standard] gradio pydantic')
  .runCmd('pip install -q python-dotenv rich typer pathlib2')
  .runCmd('mkdir -p /home/user/outputs/model /home/user/outputs/plots /home/user/outputs/data /home/user/outputs/reports')
  .setWorkdir('/home/user')
  .copy('start.sh', '/start.sh')
  .runCmd('chmod +x /start.sh')
  .setUser('user')
  .setStartCmd('sudo /start.sh', 'sleep 20')